
name: PassWifi

# <--- THÃŠM DÃ’NG NÃ€Y VÃ€O FILE Cá»¦A Báº N
run-name: ${{ github.workflow }} - Wifi: ${{ github.event.inputs.target_url }}

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'The Wifi to test, provided by the web UI'
        required: true
        default: 'TÃªn Wifi Máº·c Äá»‹nh' # GiÃ¡ trá»‹ nÃ y sáº½ Ä‘Æ°á»£c ghi Ä‘Ã¨ bá»Ÿi trang web

jobs:
  certapple-run:
    name: Run Passwifi Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Passwifi test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ðŸ’¹ðŸ’¹ðŸ’¹Passwifi.js
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
